# Generated by Django 5.2.1 on 2025-05-19 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo_ambiente', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Batalha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('local', models.CharField(max_length=100)),
                ('perdedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='derrotas', to='torneio.treinador')),
                ('vencedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitorias', to='torneio.treinador')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('efeito', models.TextField()),
                ('quantidade', models.IntegerField()),
                ('treinador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torneio.treinador')),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('nivel', models.IntegerField()),
                ('treinador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torneio.treinador')),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('treinadores', models.ManyToManyField(to='torneio.treinador')),
            ],
        ),
    ]
