# Generated by Django 5.2.1 on 2025-05-19 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneio', '0002_local_batalha_item_pokemon_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='quantidade',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='local',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='time',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='treinador',
            unique_together={('nome', 'cidade')},
        ),
        migrations.CreateModel(
            name='TreinadorTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torneio.time')),
                ('treinador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torneio.treinador')),
            ],
            options={
                'unique_together': {('treinador', 'time')},
            },
        ),
    ]
